"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Check, Shield, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
type Edit = { id:string; spotify_track_id:string; lyrics:unknown[]; users:{username:string}|null };
type Report = { id:string; spotify_track_id:string; observed_offset_ms:number; status:string };
export default function AdminPage(){
 const [allowed,setAllowed]=useState<boolean|null>(null),[edits,setEdits]=useState<Edit[]>([]),[reports,setReports]=useState<Report[]>([]),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const {data:admin}=await supabase.rpc("is_admin");setAllowed(!!admin);if(!admin)return;const [a,b]=await Promise.all([supabase.from("lyric_edits").select("id,spotify_track_id,lyrics,users(username)").eq("moderation_status","pending").order("updated_at"),supabase.from("lyric_reports").select("id,spotify_track_id,observed_offset_ms,status").neq("status","resolved").order("updated_at")]);setEdits((a.data||[]) as unknown as Edit[]);setReports((b.data||[]) as Report[]);},[]);
 useEffect(()=>{void load();},[load]);
 const moderate=async(id:string,decision:"approved"|"rejected")=>{const {error}=await supabase.rpc("moderate_lyric_edit",{target_edit:id,decision});setMessage(error?.message||`Corrección ${decision==="approved"?"aprobada":"rechazada"}.`);await load();};
 const resolve=async(id:string)=>{const {error}=await supabase.rpc("resolve_lyric_report",{target_report:id,decision:"resolved"});setMessage(error?.message||"Reporte resuelto.");await load();};
 if(allowed===null)return <main className="grid min-h-screen place-items-center bg-[#07080d] text-zinc-400">Comprobando permisos…</main>;
 if(!allowed)return <main className="grid min-h-screen place-items-center bg-[#07080d] text-white"><div className="text-center"><Shield className="mx-auto mb-4 text-red-300"/><h1 className="text-2xl font-black">Acceso restringido</h1><Link href="/" className="mt-5 inline-block text-violet-300">Volver al juego</Link></div></main>;
 return <main className="min-h-screen bg-[#07080d] p-6 text-white"><div className="mx-auto max-w-5xl"><Link href="/" className="text-violet-300">← Volver</Link><h1 className="mt-5 text-3xl font-black">Moderación</h1>{message&&<p className="mt-4 rounded-xl bg-white/5 p-3">{message}</p>}<h2 className="mt-8 text-xl font-bold">Correcciones pendientes ({edits.length})</h2><div className="mt-3 space-y-3">{edits.map(e=><article key={e.id} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><b>{e.spotify_track_id}</b><span className="ml-3 text-sm text-zinc-500">{e.users?.username||"Usuario"} · {e.lyrics.length} líneas</span><div className="mt-3 flex gap-2"><button onClick={()=>moderate(e.id,"approved")} className="flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2 font-bold"><Check size={16}/>Aprobar</button><button onClick={()=>moderate(e.id,"rejected")} className="flex items-center gap-2 rounded-xl bg-red-500/20 px-4 py-2 text-red-200"><X size={16}/>Rechazar</button></div></article>)}</div><h2 className="mt-8 text-xl font-bold">Reportes abiertos ({reports.length})</h2><div className="mt-3 space-y-3">{reports.map(r=><article key={r.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.04] p-4"><span><b>{r.spotify_track_id}</b><small className="ml-3 text-zinc-500">Offset: {r.observed_offset_ms} ms</small></span><button onClick={()=>resolve(r.id)} className="rounded-xl bg-violet-500 px-4 py-2 font-bold">Resolver</button></article>)}</div></div></main>;
}
